src/Entity/Ingridient.php
<?php

namespace App\Entity;

use App\Repository\IngridientRepository;
use Doctrine\ORM\Mapping as ORM;
use Laminas\Code\Reflection\FunctionReflection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=IngridientRepository::class)
 */
class Ingridient
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }
}

templates/catalogue/details.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h1 class="text-center">{{ page_title }}</h1>

	<a href="{{ path('index') }}">&#60;&#60;Back to Pizza list</a>


	<div class="card-content-wrapper">
		<div class="card details-content" style="width: 40rem;">

			<div class="card-body">
				<div class="container text-center">
					<div class="row">
						<div class="col">
							<h2>Ingridients</h2>

						</div>
						<div class="col">
							<button type="button" class="btn btn-success">Add ingridient</button>

						</div>

					</div>
				</div>

				<table class="table">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Name</th>
							<th scope="col">Price</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for ingridient in ingridient_list %}

							<tr>
								<th scope="row">{{ ingridient.id }}</th>

								<td>{{ ingridient.name }}</td>

								<td>{{ ingridient.price }}€</td>

								<td>
									<button type="button" class="btn btn-success">Edit</button>
									<button type="button" class="btn btn-danger">Remove</button>
								</td>
							</tr>
						{% endfor %}

					</tbody>
				</table>

			</div>
		</div>
	</div>
{% endblock %}

templates/catalogue/pizza.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<h1 class="text-center">{{ page_title }}</h1>

	<div class="card-content-wrapper">
		<div class="card details-content" style="width: 40rem;">
			<div class="card-body">
				<button type="button" class="btn btn-success">Add Pizza</button>

				<table class="table">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Name</th>
							<th scope="col">Price</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for pizza in pizza_list %}
							<tr>
								<th scope="row">{{ pizza.id }}</th>

								<td>{{ pizza.name }}</td>
								<td>{{ pizza.price }}€</td>
								<td>
									<a href="{{ path('details', {id: pizza.id}) }}" type="button" class="btn btn-secondary">Details</a>
									<button type="button" class="btn btn-danger">Remove</button>
								</td>
							</tr>
						{% endfor %}

					</tbody>
				</table>

			</div>
		</div>

	</div>
{% endblock %}